### ISSUE TITLE
Home Assistant 0.91.4 error

### ISSUE THREAD

**Issue by pbouwen3** [heinoldenhuis/home_assistant_omnik_solar#1]
Hi!

Just tried to install it on my Home Assistant 0.91.4 server, but it doesn't seem to work.
I get the following error:

> Integrations need to be in their own folder. Change sensor/omnik.py to omnik/sensor.py. This will stop working soon.

Are you running an older version of HA, or do you know how I can resolve this?

Thanks in advance!

**Comment by heinoldenhuis** [comment]
Hi!

I have updated the sources so it will work on 0.91.4 and up to 0.92.1.
Currently I am running Home Assistant 0.92.1.

Regards, Hein

**Comment by heinoldenhuis** [comment]
Issue fixed

**Comment by pbouwen3** [comment]
Thanks Hein!!
