### ISSUE TITLE
Unstable

### ISSUE THREAD

**Issue by PierreLevres** [heinoldenhuis/home_assistant_omnik_solar#12]
The scrips/integration is pretty unstable here.
For a few hours a day it functions, and then it stops functioning, with message "Updating omnik sensor took longer than the scheduled update interval 0:01:00" 

When I run the script Livestats.py from https://github.com/Woutrrr/Omnik-Data-Logger every minute, it works perfectly and doesn't stop.

I experimented with 3 changes on your code, it is pretty stable now:
- to avoid zeroes in the logging when missing a request, add a condition before calling update_values (line 255 in sensor.py)
- connect with a specific protocol to the inverter (line 307)
- add timeout to the socket connection (line 308)

Let you know how it evolves...

**Comment by hartmanrik** [comment]
Please keep us posted, same I'm experiencing the behaviour

**Comment by PierreLevres** [comment]
no more errors in the log so far.... and no zero-spikes when a connect fails. 
i will undo my second change, and see what happens, if that remains stable for a few days i will submit a PR

**Comment by PierreLevres** [comment]
I submitted the PR a few days ago, with the two changes. My readings are stable, and no more errors in the log, no more zero lines. 
<img width="1383" alt="Screenshot 2021-07-11 at 12 31 10" src="https://user-images.githubusercontent.com/62832923/125191749-4ea4aa80-e244-11eb-9b73-97f85f3e4e14.png">
