### ISSUE TITLE
dcinputvoltage dcinputcurrent for two strings

### ISSUE THREAD

**Issue by tomekso** [heinoldenhuis/home_assistant_omnik_solar#17]
Can someone advice me how to setup HA to get data dcinputvoltage dcinputcurrent from two strings?

**Comment by rhuit** [comment]
Try this little patch so you can read your second string from your converter:

--- /root/omnik/sensor.py     2021-12-27 11:21:33.286786525 +0100
+++ omnik/sensor.py   2021-12-27 11:19:29.146161119 +0100
@@ -66,6 +66,8 @@
     'temperature':       ['Temperature', '°C', 'mdi:thermometer', DEVICE_CLASS_TEMPERATURE, STATE_CLASS_MEASUREMENT],
     'dcinputvoltage':    ['DC Input Voltage', 'V', 'mdi:flash-outline', DEVICE_CLASS_VOLTAGE, STATE_CLASS_MEASUREMENT],
     'dcinputcurrent':    ['DC Input Current', 'A', 'mdi:flash-outline', DEVICE_CLASS_CURRENT, STATE_CLASS_MEASUREMENT],
+    'dcinputvoltage2':    ['DC Input Voltage 2', 'V', 'mdi:flash-outline', DEVICE_CLASS_VOLTAGE, STATE_CLASS_MEASUREMENT],
+    'dcinputcurrent2':    ['DC Input Current 2', 'A', 'mdi:flash-outline', DEVICE_CLASS_CURRENT, STATE_CLASS_MEASUREMENT],
     'acoutputvoltage':   ['AC Output Voltage', 'V', 'mdi:flash-outline', DEVICE_CLASS_VOLTAGE, STATE_CLASS_MEASUREMENT],
     'acoutputcurrent':   ['AC Output Current', 'A', 'mdi:flash-outline', DEVICE_CLASS_CURRENT, STATE_CLASS_MEASUREMENT],
     'acoutputfrequency': ['AC Output Frequency', 'Hz', 'mdi:flash-outline', None, STATE_CLASS_MEASUREMENT],
@@ -243,6 +245,10 @@
       value = self.interface_inverter.get_dcinputvoltage()
     elif(sensor_type == 'dcinputcurrent'):
       value = self.interface_inverter.get_dcinputcurrent()
+    elif(sensor_type == 'dcinputvoltage2'):
+      value = self.interface_inverter.get_dcinputvoltage(2)
+    elif(sensor_type == 'dcinputcurrent2'):
+      value = self.interface_inverter.get_dcinputcurrent(2)
     elif(sensor_type == 'acoutputvoltage'):
       value = self.interface_inverter.get_acoutputvoltage()
     elif(sensor_type == 'acoutputcurrent'):

Maybe this can be added as patch for converters with multiple strings.
(but than probably, there needs to be a configuration item to enable/disable this)
