### ISSUE TITLE
device_state_attributes

### ISSUE THREAD

**Issue by tomekso** [heinoldenhuis/home_assistant_omnik_solar#18]
Hi,

I'm getting warnings on Home Assistant 2021.12.1: 

Logger: homeassistant.helpers.entity
Source: helpers/entity.py:549

    Entity sensor.myomnik_dc_input_current (<class 'custom_components.omnik.sensor.OmnikSensor'>) implements device_state_attributes. Please report it to the custom component author.
    Entity sensor.myomnik_ac_output_voltage (<class 'custom_components.omnik.sensor.OmnikSensor'>) implements device_state_attributes. Please report it to the custom component author.
    Entity sensor.myomnik_ac_output_current (<class 'custom_components.omnik.sensor.OmnikSensor'>) implements device_state_attributes. Please report it to the custom component author.
    Entity sensor.myomnik_ac_output_frequency (<class 'custom_components.omnik.sensor.OmnikSensor'>) implements device_state_attributes. Please report it to the custom component author.
    Entity sensor.myomnik_ac_output_power (<class 'custom_components.omnik.sensor.OmnikSensor'>) implements device_state_attributes. Please report it to the custom component author.

**Comment by mdcobra** [comment]
I have replaced line 151 with:
`    def device_extra_state_attributes(self):`
