### ISSUE TITLE
Sensors not showing information

### ISSUE THREAD

**Issue by Vievje** [heinoldenhuis/home_assistant_omnik_solar#9]
After updating Home Assistant to 0.113.3 and Hacs to 1.3.1 the sensors are not showing any information anymore. Before the update it was working great, do I need to change something?

**Comment by Sjorsa** [comment]
I'm using two inverters, and one of them works and the other one has the same problem as yours, although it also didn't work before 0.113.

**Comment by danielroek** [comment]
Same problem running HACS 1.5.1 on Home Assistant Core 0.114.3:
`Updating omnik sensor took longer than the scheduled update interval`
